version: '3.8'

services:
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parking_management
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - webnet

networks:
  webnet:
    external: true
